### ISSUE TITLE
Duration in the list is different from an actual duration

### ISSUE THREAD

**Issue by Laritello** [Laritello/osu-music#23]
![image](https://user-images.githubusercontent.com/29901577/143138167-82220979-a0e0-4b36-859b-31632e245d12.png)

**Comment by Shmalle** [comment]
That also causes a few seconds delay between actually being able to hear the song between that it has started

**Comment by Laritello** [comment]
@Shmalle are you sure it's not audio files themself have delay?

**Comment by Shmalle** [comment]
Oh, well, yea there is a delay even if I run it on groove or any other music player. As it turns out, it must be some osu-audio-thing that causes it hence the song itself (as in any tone) goes from 00:04 to 01:35. Before and after those two timestamps, theres no tone played.

**Comment by Laritello** [comment]
Long story short, total time in osu.db show total time of the map (which is shown in osu itself) not the total time of the audio.
The fix to this is to read each individual file and then get it duration, which will lead to a terrible increase in time required to read the database.

Personally, I find this issue too minor to spend so much time reworking loading routine. At least, for now.
