### ISSUE TITLE
Receiving errors when running/updating

### ISSUE THREAD

**Issue by Shmalle** [Laritello/osu-music#26]
I cloned the repo and ran it, just got errors with the modules. CTRL+C gave me a red warning, that the Build-process is being cancelled, then the build.bat file didnt work and just gave errors.
EDIT:  I gave it another try. This time with git clone and build.bat. I was able to build with 20 warnings and 0 errors. Running it made it running for approx. 4 seconds, then it crashed.

**Comment by Shmalle** [comment]
It was just the AppData thing again, sorry for the inconvenience!

**Comment by Laritello** [comment]
I pushed some changes, that should fix crashes. However, I'm worried that its crash may be caused by corrupted settings.json. So if you face same issues in the future before deleting settings.json please check if it's not corrupted.
