### ISSUE TITLE
xx:xx elapsed in Discord isnt stopping

### ISSUE THREAD

**Issue by Shmalle** [Laritello/osu-music#27]
So when I paused the song, the timer within the RPC kept running.
![image](https://user-images.githubusercontent.com/72462771/143484855-f1694745-c964-4068-8efa-87e3bfd1b84c.png)
Starting another song makes it restart though.

**Comment by Laritello** [comment]
Yeah, my bad. I update status only when beatmap changes, but not the state of the playback.
