### ISSUE TITLE
Directly fetch mp3 

### ISSUE THREAD

**Issue by Shmalle** [Laritello/osu-music#29]
A nice thing would be that one could simply right-click a song or a button and be redirected to the folder of that song containing the .mp3 file. Example:
![image](https://user-images.githubusercontent.com/72462771/144116873-6b7f8cae-2a1c-478d-8803-33ad6e2c5ede.png)

**Comment by Laritello** [comment]
Right-click on the beatmap that you want to open.
![image](https://user-images.githubusercontent.com/29901577/172029285-178a9574-e1f8-4c87-b6bb-b65dc13e772f.png)
