### ISSUE TITLE
Add installation guide

### ISSUE THREAD

**Issue by Shmalle** [Laritello/osu-music#5]
A guide on how to install the program would be very nice of you. I had to figure out how it works and [fsr](https://www.urbandictionary.com/define.php?term=fsr) managed to do so. I installed .NET 6 and did "dotnet run", then had to figure out I needed .NET core 3.1 Desktop, now its running! Thanks for making this program.

**Comment by Laritello** [comment]
Hi! Glad you liked the program. I was planning on adding a proper installer/updater but unfortunately kinda short on time right now.  :(
You can find archive with portable version in release section, but  adding build guide is a good idea as well.
