### ISSUE TITLE
Add Discord-RPC

### ISSUE THREAD

**Issue by Shmalle** [Laritello/osu-music#6]
A Discord-RPC would be cool! Something like this:
![image](https://user-images.githubusercontent.com/72462771/141869170-3bac7958-dd4c-40ad-ba45-2488ebef103c.png)

(I just edited the HTML to show what I mean)

**Comment by Laritello** [comment]
Sounds good. I'll look into it.

**Comment by Laritello** [comment]
As far as I understand, Discord made custom Rich Presence for Spotify. As for other applications it gives fixed fields developer can display. So it's kinda impossible to achieve what you've shown, but maybe I'll do something with it in the future.
![image](https://user-images.githubusercontent.com/29901577/142275053-7c639043-d0b0-47fe-b1f8-83744e340701.png)

**Comment by Shmalle** [comment]
Well I was able to reproduce an RPC on my Account as well, here's an example of soemthing that I found just to have an instance: 
![image](https://user-images.githubusercontent.com/72462771/142496001-20e6b47d-764c-439e-8bcc-b6cee50ddbee.png)
(Will add mine once I got it set up, forgot where it was)

**Comment by Laritello** [comment]
Yeah something like that is totally doable.
