### ISSUE TITLE
Add functionkey/mediakey ability

### ISSUE THREAD

**Issue by Shmalle** [Laritello/osu-music#7]
It would be cool if one could use Mediakeys or Functionkeys (FN+F7 for example to Skip) with Osu.Music!
![image](https://user-images.githubusercontent.com/72462771/141871668-774313c2-ba94-42e7-a260-47ddc8557ccd.png)

**Comment by Shmalle** [comment]
I updated the clone and tried to use a hotkey several times but it just crashes the program for some reason. Everything else is running fine

https://user-images.githubusercontent.com/72462771/142771850-d18eda11-407b-48b6-b930-9dbfcc0d7bd3.mp4

!

**Comment by Laritello** [comment]
Hmm... Did you changed any of the hotkeys? If you did, please send me screenshot. Meanwhile I check what could be a potential reason.

**Comment by Shmalle** [comment]
We found the fix! We had to delete the AppData/Romaing/osu.Music folder in order to see the Hotkey-settings.

**Comment by Laritello** [comment]
Oh, thanks for the info. I've opened a separate issue #13 for this bug.
